//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ledger_master
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> under_id { get; set; }
        public string billing_style { get; set; }
        public Nullable<decimal> opening_balance { get; set; }
        public Nullable<int> credit_debit_type { get; set; }
        public string print_name { get; set; }
        public string owner_name { get; set; }
        public string address { get; set; }
        public Nullable<int> state { get; set; }
        public string pin_code { get; set; }
        public string mobile { get; set; }
        public string aadhar_no { get; set; }
        public string email { get; set; }
        public string area { get; set; }
        public Nullable<int> agent { get; set; }
        public Nullable<bool> interest { get; set; }
        public Nullable<int> credit_priod { get; set; }
        public Nullable<int> less_priod { get; set; }
        public Nullable<decimal> interest_rate { get; set; }
        public string description { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
    }
}
