//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_master
    {
        public int id { get; set; }
        public string product { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> item_group_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> unit_id { get; set; }
        public Nullable<int> alternat_unit_id { get; set; }
        public Nullable<decimal> mrp { get; set; }
        public Nullable<int> rate_on { get; set; }
        public Nullable<int> tax_type { get; set; }
        public Nullable<int> sale_rate_on { get; set; }
        public Nullable<decimal> rate_persantage { get; set; }
        public Nullable<decimal> discount_consumer { get; set; }
        public Nullable<decimal> discount_other { get; set; }
        public Nullable<decimal> discount_on_qty { get; set; }
        public Nullable<decimal> brokerage { get; set; }
        public Nullable<decimal> min_qty { get; set; }
        public Nullable<decimal> order_qty { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
    }
}
