//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_expenses_master
    {
        public int id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<decimal> adhat { get; set; }
        public Nullable<int> adhat_unit_id { get; set; }
        public Nullable<decimal> taulai { get; set; }
        public Nullable<int> taulai_unit_id { get; set; }
        public Nullable<decimal> majoori { get; set; }
        public Nullable<int> majoori_unit_id { get; set; }
        public Nullable<decimal> packing { get; set; }
        public Nullable<int> packing_unit_id { get; set; }
        public Nullable<decimal> mandi_sulk { get; set; }
        public Nullable<int> mandi_sulk_unit_id { get; set; }
        public Nullable<decimal> vikash_sesh { get; set; }
        public Nullable<int> vikash_sesh_unit_id { get; set; }
        public Nullable<decimal> packing_less { get; set; }
        public Nullable<int> packing_less_unit_id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
    }
}
