//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_master
    {
        public int purchase_id { get; set; }
        public Nullable<int> serial_no { get; set; }
        public Nullable<int> book_no { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
        public Nullable<int> party_name_id { get; set; }
        public Nullable<int> supplier_invoice_no { get; set; }
        public Nullable<System.DateTime> purchase_date1 { get; set; }
        public Nullable<decimal> gross_amount { get; set; }
        public Nullable<decimal> paking_amount { get; set; }
        public Nullable<double> dis_persantage { get; set; }
        public Nullable<decimal> dis_amount { get; set; }
        public Nullable<decimal> other_charges { get; set; }
        public Nullable<decimal> round_off { get; set; }
        public Nullable<decimal> net_amount { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> status { get; set; }
    }
}
