//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_expenses
    {
        public int id { get; set; }
        public Nullable<int> sales_id { get; set; }
        public Nullable<decimal> adhat { get; set; }
        public Nullable<decimal> taulai { get; set; }
        public Nullable<decimal> majoori { get; set; }
        public Nullable<decimal> packing { get; set; }
        public Nullable<decimal> mandi_sulk { get; set; }
        public Nullable<decimal> vikash_sesh { get; set; }
        public Nullable<decimal> other { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<int> company_id { get; set; }
    }
}
