//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class under_master
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
    }
}
